-- MySQL Script generated by MySQL Workbench
-- lun. 16 mai 2022 22:32:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FinDevComp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FinDevComp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FinDevComp` ;
USE `FinDevComp` ;

-- -----------------------------------------------------
-- Table `FinDevComp`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinDevComp`.`type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinDevComp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinDevComp`.`users` (
  `id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(75) NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `city` VARCHAR(75) NOT NULL,
  `cp` INT(5) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `id_type` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_type`),
  INDEX `fk_users_Type_idx` (`id_type` ASC) VISIBLE,
  CONSTRAINT `fk_users_Type`
    FOREIGN KEY (`id_type`)
    REFERENCES `FinDevComp`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinDevComp`.`type_charge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinDevComp`.`type_charge` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinDevComp`.`charge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinDevComp`.`charge` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(150) NOT NULL,
  `cost` INT NOT NULL,
  `type_charge_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `type_charge_id`),
  INDEX `fk_charge_type_charge1_idx` (`type_charge_id` ASC) VISIBLE,
  CONSTRAINT `fk_charge_type_charge1`
    FOREIGN KEY (`type_charge_id`)
    REFERENCES `FinDevComp`.`type_charge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinDevComp`.`bdd_finance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinDevComp`.`bdd_finance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `compte` INT NOT NULL,
  `label` VARCHAR(150) NOT NULL,
  `annual_cost` INT NOT NULL,
  `year` INT NOT NULL,
  `percentage` INT NOT NULL,
  `cost_structure_percentage` INT NOT NULL,
  `ER_n` INT NOT NULL,
  `ER_n-1` INT NOT NULL,
  `maintenance_and_repair` INT NOT NULL,
  `structural_cost` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinDevComp`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinDevComp`.`client` (
  `id` INT UNSIGNED NOT NULL,
  `name_company` VARCHAR(75) NOT NULL,
  `first_name` VARCHAR(75) NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `city` VARCHAR(75) NOT NULL,
  `cp` INT(5) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinDevComp`.`estimate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinDevComp`.`estimate` (
  `id` INT UNSIGNED NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  `client_id` INT UNSIGNED NOT NULL,
  `date_estimate` VARCHAR(45) NOT NULL,
  `unit_cost` INT NOT NULL,
  `number_day` INT NOT NULL,
  `HT` INT NOT NULL,
  `TVA` INT NOT NULL,
  `TTC` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `client_id`),
  INDEX `fk_estimate_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_estimate_client1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_estimate_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `FinDevComp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estimate_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `FinDevComp`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinDevComp`.`total_bdd_finance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinDevComp`.`total_bdd_finance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(150) NOT NULL,
  `cost` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
